#ifndef APP_VERSION_H
#define APP_VERSION_H

#define APP_VERSION_MAJOR 2U
#define APP_VERSION_MINOR 0U
#define APP_VERSION_PATCH 0U
#define APP_VERSION_BUILD 0U

#define APP_VERSION_PACKED 0x02000000U
#define APP_VERSION_TEXT   "V2.0"

#endif /* APP_VERSION_H */
